# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       libxkbcommon

# >> macros
# << macros

Summary:    Xorg X11 common xkb library
Version:    0.3.2
Release:    1
Group:      System/Libraries
License:    MIT
URL:        http://www.x.org/
Source0:    libxkbcommon-%{version}.tar.bz2
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  byacc
BuildRequires:  libtool
BuildRequires:  flex
BuildRequires:  bison

%description
xkb Libraries file.

%package devel
Summary:    Xorg X11 common xkb libray
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
xkb Development Libraries file.


%prep
%setup -q -n %{name}-%{version}/%{name}

# >> setup
# << setup

%build
# >> build pre
# << build pre

CFLAGS="-std=c99" %autogen --disable-static \
    --with-xkb-config-root=/usr/share/X11/xkb

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post


%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
# >> files
%{_libdir}/libxkbcommon.so.0
%{_libdir}/libxkbcommon.so.0.0.0
# << files

%files devel
%defattr(-,root,root,-)
# >> files devel
#%{_libdir}/extensions/XKBcommon.h
%{_includedir}/xkbcommon/xkbcommon.h
%{_includedir}/xkbcommon/xkbcommon-names.h
%{_includedir}/xkbcommon/xkbcommon-keysyms.h
%{_includedir}/xkbcommon/xkbcommon-compat.h
%{_libdir}/libxkbcommon.so
%{_libdir}/pkgconfig/xkbcommon.pc
# << files devel
